import logging
from typing import Any

class JsonFormatter(logging.Formatter):
    format_dict: Any = ...
    default_json_formatter: Any = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def format(self, record: Any): ...

def setupLogger(level: str = ..., formatter_cls: Any = ..., boto_level: Any | None = ..., **kwargs: Any) -> None: ...
